import { useState } from 'react'
import { HelpCircle } from 'lucide-react'

const GLOSSARY: Record<string, string> = {
  WACC: 'Weighted Average Cost of Capital — the blended required rate of return for a company\'s investors, used to discount future cash flows.',
  DCF: 'Discounted Cash Flow — a valuation method that estimates the present value of future free cash flows, discounted at the WACC.',
  FCF: 'Free Cash Flow — cash generated after operating expenses and capital expenditures. The primary input to a DCF model.',
  EV: 'Enterprise Value — total company value including debt and excluding cash. EV = Market Cap + Net Debt.',
  EBITDA: 'Earnings Before Interest, Taxes, Depreciation & Amortisation — a proxy for operating cash flow used in valuation multiples.',
  'Terminal Value': 'The present value of all cash flows beyond the explicit projection period, calculated using the Gordon Growth Model.',
  'Integration Cost': 'One-time costs to merge two companies: restructuring, system integration, redundancy payments, and advisory fees.',
  'Revenue Synergy': 'Additional revenue generated by the combined entity through cross-selling, expanded market reach, or pricing power.',
  'Cost Synergy': 'Savings from eliminating redundant headcount, overlapping R&D, shared infrastructure, and procurement scale.',
  'Accretion / Dilution': 'Whether the merger increases (accretive) or decreases (dilutive) the acquirer\'s earnings per share post-close.',
  'Implied Premium': 'The additional value the combined entity creates above the simple sum of the two standalone enterprise values.',
}

interface TooltipProps {
  term: string
  children?: React.ReactNode
}

export function FinancialTooltip({ term, children }: TooltipProps) {
  const [visible, setVisible] = useState(false)
  const definition = GLOSSARY[term]

  if (!definition) return <>{children}</>

  return (
    <span className="relative inline-flex items-center gap-1">
      {children}
      <button
        className="text-slate-500 hover:text-slate-300 transition-colors"
        onMouseEnter={() => setVisible(true)}
        onMouseLeave={() => setVisible(false)}
        onFocus={() => setVisible(true)}
        onBlur={() => setVisible(false)}
        aria-label={`Definition of ${term}`}
        type="button"
      >
        <HelpCircle className="h-3.5 w-3.5" />
      </button>
      {visible && (
        <span className="absolute bottom-full left-0 z-50 mb-1 w-64 rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-xs text-slate-300 shadow-xl">
          <span className="block font-semibold text-slate-100">{term}</span>
          {definition}
        </span>
      )}
    </span>
  )
}
